// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $signin_index from "./routes/signin/index.tsx";
import * as $signin_islands_SignInForm from "./routes/signin/(_islands)/SignInForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/signin/index.tsx": $signin_index,
  },
  islands: {
    "./routes/signin/(_islands)/SignInForm.tsx": $signin_islands_SignInForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
